# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_auto_20180524_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_model',
            name='email',
            field=models.EmailField(default='oop@qq.com', max_length=254),
        ),
        migrations.AddField(
            model_name='test_model',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1),
        ),
    ]
