# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-01 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0004_auto_20180524_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='testb_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(default='oop@qq.com', max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn'), ('g', 'gangzi')], default='d', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='test_model',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn'), ('g', 'gangzi')], default='d', max_length=1),
        ),
    ]
