# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-11 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0005_auto_20180601_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_model',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
