# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontauth.frontAuthModel'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.CategoryModel'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='read_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supportmodel',
            name='status',
            field=models.CharField(choices=[('0', 'give up support!'), ('1', 'support')], max_length=1),
        ),
    ]
