# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-05 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmodel',
            name='status',
            field=models.CharField(choices=[('0', 'give up support!'), ('1', 'support')], max_length=1),
        ),
        migrations.AlterField(
            model_name='topmodel',
            name='top_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
