# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontauth', '0002_frontauthmodel_regist_time'),
        ('article', '0002_auto_20180711_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_type', models.IntegerField()),
                ('reply_id', models.IntegerField()),
                ('content', models.CharField(max_length=500)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.CommentModel')),
                ('from_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_commentreply', to='frontauth.frontAuthModel')),
                ('to_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_commentreply', to='frontauth.frontAuthModel')),
            ],
        ),
    ]
