# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-29 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180629_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
