# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-16 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_commentreplymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supportmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', related_query_name='supports', to='article.ArticleModel'),
        ),
    ]
