# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180629_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supportmodel',
            name='status',
            field=models.CharField(choices=[('1', 'support'), ('0', 'give up support!')], max_length=1),
        ),
    ]
