# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authReationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('1', 'attention'), ('2', 'fans')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='frontAuthModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('tel', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='authreationmodel',
            name='authA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authAs', to='frontauth.frontAuthModel'),
        ),
        migrations.AddField(
            model_name='authreationmodel',
            name='authB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authBs', to='frontauth.frontAuthModel'),
        ),
    ]
