# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-17 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontauth', '0002_frontauthmodel_regist_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authreationmodel',
            name='relation_type',
            field=models.CharField(choices=[('1', 'fans each othor'), ('0', 'only i attenion you')], max_length=1),
        ),
    ]
